# [START gae_python37_cloudsql_config]
runtime: python37

env_variables:
  CLOUD_SQL_USERNAME: root
  CLOUD_SQL_PASSWORD: prueba
  CLOUD_SQL_DATABASE_NAME: prueba
  CLOUD_SQL_CONNECTION_NAME: prueba-api-294023:us-central1:prueba-api
# [END gae_python37_cloudsql_config]
